name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  check-tag:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create version env variables
        run: |
          VERSION_NPM=$(jq -r '.version' package.json)
          echo "VERSION_NPM=${VERSION_NPM}" >> $GITHUB_ENV
          echo "VERSION_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: fail job if version check fails
        run: |
          if [ "$VERSION_NPM" != "$VERSION_TAG" ]; then
            echo "NPM version $VERSION_NPM does not match the tag $VERSION_TAG"
            exit 1
          fi

  build:
    name: build NPM package
    runs-on: ubuntu-latest
    needs: check-tag
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
      - name: install packages
        run: npm ci
        env:
          GITHUB_TOKEN: ${{ secrets.API_PKG_PAT }}
      - name: build application
        run: npm run build-prod
      - name: upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: kant-search-frontend
          path: dist/kant-search-frontend

  publish-docker:
    name: publish Docker image
    runs-on: ubuntu-latest
    needs: build
    env:
      OWNER: ${{ github.repository_owner }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: adjust env variables
        run: |
          echo "OWNER=$(echo $OWNER | awk '{print tolower($0)}')" >> $GITHUB_ENV
      - name: download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: kant-search-frontend
          path: kant-search-frontend
      - name: build Docker image
        run: |
          docker build \
            -f ./deployment/Dockerfile \
            -t ghcr.io/frhorschig/kant-search-frontend:latest \
            .
      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: publish docker image
        run: |
          img=ghcr.io/${{ env.OWNER }}/${{ env.REPO_NAME }}
          version=${{ github.ref_name }}
          docker tag  $img $img:$version
          docker tag  $img $img:latest
          docker push $img:$version
          docker push $img:latest

  publish-js:
    name: publish JavaScript files
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download the build artifact
        uses: actions/download-artifact@v4
        with:
          name: kant-search-frontend
          path: kant-search-frontend
      - name: zip Angular files
        run: |
          zip -r kant-search-frontend.zip kant-search-frontend
      - name: create release
        uses: softprops/action-gh-release@v2.0.4
        with:
          tag_name: ${{ github.ref_name }}
          files: kant-search-frontend.zip
          token: ${{ secrets.GITHUB_TOKEN }}
